### ISSUE TITLE
Julia 0.7-DEV

### ISSUE THREAD

**Issue by Nosferican** [JuliaNLSolvers/Optim.jl#587] opened 2018-04-11 20:04 UTC
Wanted to get a sense or stage of the plans to release a Julia 0.7-DEV version. Getting a timeline would allow me to know an estimated date to schedule some update tasks that depends on Optim.

**Comment by pkofod** [comment] 2018-04-11 20:51
There are PRs in all related packages, but I'm not sure how far they are from being mergeable @chriselrod

**Comment by pkofod** [comment] 2018-04-12 05:32
Do you mean a tagged version by the way, or a version of master?

**Comment by chriselrod** [comment] 2018-04-12 11:19
I can spend a few hours this weekend, but when it comes to just the Julia 0.7 stuff, you may be able to handle it better.

I'll check again, but I think the remaining test failures fell into one of two categories:

1. Recursive arrays not supporting 0.7 yet
2. Convergence failures on 0.7 that didn't happen on 0.6. In some problems (particularly Newton), there are different numbers of iterations even when they do converge and also the occasional convergence failure by increasing objective on 0.7 that didn't happen on 0.6.

That last one is probably something you ought to look into. I dumped a bunch of info on gitter about a week ago, but I can try and organize things more and better point to the particular tests.

**Comment by pkofod** [comment] 2018-04-12 12:26
I'm building master to see if I can get it up and running

**Comment by Nosferican** [comment] 2018-06-06 13:34
Probably a good time to get it working with `v"0.7-alpha"`.

**Comment by anriseth** [comment] 2018-06-06 14:01
Have you tried it on 0.7? What if you run it with #607?

I think many people in the community are waiting for femtocleaner to help with the transition.

**Comment by Nosferican** [comment] 2018-06-06 14:04
`femtocleaner` is live (or it was a few days ago). If it is missing depreciations, those can be reported to the repository to update the depreciations (and speed the process). I haven't tried it with PR607.

**Comment by anriseth** [comment] 2018-06-06 14:17
The permission bump in femtocleaner is not the same as it being ready for 0.7, but if you have another source that proves me wrong that's good news.
( I assume you are referring to https://discourse.julialang.org/t/psa-femtocleaner-permissions-change-incoming/11423 )

**Comment by Nosferican** [comment] 2018-06-06 14:19
Probably not ready yet, but it was live (it was down for a long time) a few days ago (I got a few femtocleaner PR for some repos).

**Comment by pkofod** [comment] 2018-06-06 14:46
The reason why I havn't done anything yet (I've been at it two times) is because of all the changes to `mul!` etc. Since none of this is in Compat, I don't have the time to bother with a multiversion (v0.6 and v0.7) compatible Optim. My best bet is that at some point I'll tag a v0.7 version that Femtocleaner can clean, and then we'll drop v0.6 support. Not right now though.

**Comment by Nosferican** [comment] 2018-06-06 14:47
Thanks for the update. What's your recommendation for updating packages that depend on `Optim.jl`? Wait for the Julia 0.7 tagged version?

**Comment by Nosferican** [comment] 2018-06-06 15:05
Making a package compatible with v0.7 as well as updating lecture notes to use v0.7 syntax.

**Comment by pkofod** [comment] 2018-06-06 16:44
Well, when femtocleaner is ready then

**Comment by juliohm** [comment] 2018-06-23 01:12
Any updates on this? I am trying to update Variography.jl for Julia v0.7, but Optim.jl is not compiling yet due to the lack of NaNMath.jl

**Comment by pkofod** [comment] 2018-06-23 07:33
Well, is there an update in Femtocleaner?

**Comment by juliohm** [comment] 2018-06-24 03:15
I don't think so, but Julia v0.7-beta was tagged already :cry:

**Comment by anriseth** [comment] 2018-06-24 08:07
I don't know what nanmath has to do with this, but if you know what the problem is then a PR is welcome

**Comment by pkofod** [comment] 2018-06-24 10:48
What do you mean with nanmath? That’s not a package any of us maintain, so if the problem is with that pkg maybe we should see how it looks when they tag. Did you open a pr there?

I know it comes off as I don’t want to help, but last time I tried, I spent several hours trying to get it to work, only to realize compat was massively incomplete, so it was basically impossible to support both v06 and v07 unless I put version specific branches everywhere, that I then have to clean up again after we drop v06 support. I didn’t know beta was out, maybe we should convert soon.

**Comment by juliohm** [comment] 2018-06-24 15:51
This is what I am getting when trying to compile the package on Julia v0.7:

```julia
julia> using Optim
[ Info: Precompiling module Optim
ERROR: LoadError: ArgumentError: Module NaNMath not found in current path.
Run `Pkg.add("NaNMath")` to install the NaNMath package.
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:868
 [2] include at ./boot.jl:314 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1071
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope
 [6] eval at ./boot.jl:316 [inlined]
 [7] eval(::Expr) at ./client.jl:394
 [8] macro expansion at ./none:3 [inlined]
 [9] top-level scope at ./<missing>:0
in expression starting at /home/juliohm/.julia/packages/Optim/p3OV/src/Optim.jl:12
ERROR: Failed to precompile Optim to /home/juliohm/.julia/compiled/v0.7/Optim/R5uo.ji.
Stacktrace:
 [1] error at ./error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at ./loading.jl:1207
 [3] _require(::Base.PkgId) at ./loading.jl:1007
 [4] require(::Base.PkgId) at ./loading.jl:878
 [5] require(::Module, ::Symbol) at ./loading.jl:873
```

I totally understand the nightmare of supporting multiple versions of the language. For my packages, I am dropping support to Julia v0.6.

**Comment by anriseth** [comment] 2018-06-24 17:00
What happens if you add NaNMath manually?

LineSearches requires NaNMath, so maybe Pkg3 has missed it somehow.

**Comment by juliohm** [comment] 2018-06-24 17:47
Interestingly enough, the error persists. I am not sure what is happening. I did `add NaNMath` followed by `up`, restarted Julia and the same build error.

**Comment by fredrikekre** [comment] 2018-06-24 17:47
> LineSearches requires NaNMath, so maybe Pkg3 has missed it somehow.

No, this is a bug in Optim. In 0.7 it is illegal to [`import NaNMath`](https://github.com/JuliaNLSolvers/Optim.jl/blob/7c7e68c483e4e0fe2bb8488e1b224977a53ffcd3/src/Optim.jl#L12) unless you have it in `REQUIRE`. You can not rely on it beeing installed by `LineSearches` in this case.

**Comment by anriseth** [comment] 2018-06-24 17:59
Ah, that import crept in with IPNewton and we forgot to update REQUIRE. 

Can anybody submit a PR? I'm on my phone so can't do anything about it atm

**Comment by pkofod** [comment] 2018-06-24 19:01
Ill do it :)

**Comment by pkofod** [comment] 2018-06-25 08:16
@Nosferican @juliohm if either of you could checkout master on beta then we can see what needs to be done (nanmath is now in requires)

**Comment by Nosferican** [comment] 2018-06-25 12:55
Thanks for the updates. Will do so and report any issues if any that I can identify.

**Comment by juliohm** [comment] 2018-06-25 23:21
Thank you @pkofod , just pulled the latest master and tried to build, a new error is showing for me:

```julia
ERROR: LoadError: LoadError: syntax: invalid escape sequence
Stacktrace:
 [1] include at ./boot.jl:314 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1071
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] include(::String) at /home/juliohm/.julia/packages/Optim/6GZs/src/Optim.jl:18
 [5] top-level scope
 [6] include at ./boot.jl:314 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1071
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope
 [10] eval at ./boot.jl:316 [inlined]
 [11] eval(::Expr) at ./client.jl:394
 [12] macro expansion at ./none:3 [inlined]
 [13] top-level scope at ./<missing>:0
in expression starting at /home/juliohm/.julia/packages/Optim/6GZs/src/multivariate/solvers/first_order/ngmres.jl:66
in expression starting at /home/juliohm/.julia/packages/Optim/6GZs/src/Optim.jl:145
ERROR: Failed to precompile Optim to /home/juliohm/.julia/compiled/v0.7/Optim/R5uo.ji.
Stacktrace:
 [1] error at ./error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at ./loading.jl:1207
 [3] _require(::Base.PkgId) at ./loading.jl:1007
 [4] require(::Base.PkgId) at ./loading.jl:878
 [5] require(::Module, ::Symbol) at ./loading.jl:873
```

**Comment by anriseth** [comment] 2018-06-26 06:40
I believe the escape sequence error can be fixed by merging #607

**Comment by pkofod** [comment] 2018-06-26 12:30
I merged it just to be able to move forward. I see there are beta binaries now, so I'll see if I can find time to have a look tonight. Any reports in the mean time will only make this happen faster.

**Comment by juliohm** [comment] 2018-06-27 03:50
The master branch is now building successfully for me. A bunch of warnings, but at least it is compiling. It would be great if someone could tag a new version.

**Comment by juliohm** [comment] 2018-06-27 03:53
Tests are failing like the following:

```julia
Test Summary:                  | Pass  Error  Total
general                        |   61     11     72
  Multivariate API             |           1      1
  Univariate API               |   23            23
  callables                    |           1      1
    univariate                 |              No tests
    multivariate               |           1      1
  Callbacks                    |           1      1
  Convergence assessment       |   12            12
  default solvers              |           3      3
  Initial Convergence Handling |    2      1      3
  objective types              |   21            21
  package issues               |    1             1
  optimize                     |           1      1
  Type Stability               |           1      1
  Types                        |    2      1      3
  function counter             |           1      1
ERROR: LoadError: Some tests did not pass: 61 passed, 0 failed, 11 errored, 0 broken
```

**Comment by pkofod** [comment] 2018-06-27 06:05
I'll have a look. I tried having a quick look yesterday, but I was having some problems understanding the `Pkg3` workflow. I'll have a look tonight.

**Comment by juliohm** [comment] 2018-07-06 19:00
Any updates on Optim.jl on Julia v0.7? :)

**Comment by pkofod** [comment] 2018-07-16 13:14
Yes :) I'm on vacation, but it's pretty close to (if not there already?) being v0.7 compatible on my v0.7 branch

**Closed** 2018-08-23 12:10 UTC
