### ISSUE TITLE
optimize and Fminbox only work with Float64

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/Optim.jl#526] opened 2018-02-03 14:58 UTC
The following code only works when `T` is `Float64` but doesn't for `BigFloat` and `Float32` giving different errors. I use Optim version v0.12.0+ and Julia v0.6.2.
```julia
f(x::AbstractVector{T}) where {T} = (T(1.0) - x[1])^2 + T(100.0) * (x[2] - x[1]^2)^2
function g!(storage::AbstractVector{T}, x::AbstractVector{T}) where {T}
   storage[1] = T(-2.0) * (T(1.0) - x[1]) - T(400.0) * (x[2] - x[1]^2) * x[1]
   storage[2] = T(200.0) * (x[2] - x[1]^2)
end
T = BigFloat
lower = T[1.25, -2.1]
upper = T[Inf, Inf]
initial_x = T[2.0, 2.0]
od = OnceDifferentiable(f, g!, initial_x)
results = optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}())
```

**Comment by pkofod** [comment] 2018-02-03 15:51
I'll have a look, thanks.

**Comment by mohamed82008** [comment] 2018-02-03 16:11
Of course, sorry! Here is the error for `BigFloat`:
```julia
ERROR: MethodError: no method matching Optim.MultivariateOptimizationResults(::Optim.Fminbox{Optim.GradientDescent}, ::Bool, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::BigFloat, ::Int64, ::Bool, ::Bool, ::Float64, ::BigFloat, ::Bool, ::Float64, ::BigFloat, ::Bool, ::Float64, ::BigFloat, ::Bool, ::Array{Optim.OptimizationState{Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{BigFloat,1},Array{BigFloat,1}}}},1}, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  Optim.MultivariateOptimizationResults(::O<:Optim.AbstractOptimizer, ::Bool, ::Array{Tx,N}, ::Array{Tx,N}, ::Tf, ::Int64, ::Bool, ::Bool, ::T, ::T, ::Bool, ::T, ::T, ::Bool, ::T, ::T, ::Bool, ::M, ::Int64, ::Int64, ::Int64) where {O<:Optim.AbstractOptimizer, T, Tx, Tf, N, M} at C:\Users\user\.julia\v0.6\Optim\src\types.jl:73
Stacktrace:
 [1] #optimize#97(::BigFloat, ::BigFloat, ::BigFloat, ::Bool, ::Int64, ::Bool, ::Bool, ::Bool, ::Void, ::Int64, ::Void, ::Void, ::BigFloat, ::BigFloat, ::BigFloat, ::Optim.##98#107, ::Optim.Options{Float64,Void}, ::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:279
 [2] optimize(::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:145
```
And here is the error for `Float32`:
```julia
ERROR: c = 1.3308273992151953, lsr = LineSearches.LineSearchResults{Float32}(Float32[0.0, 0.000425865, 0.00212932, 0.0106466, 0.0532331, 0.266165, 1.33083], Float32[0.412871, 0.412811, 0.412573, 0.411411, 0.406221, 0.393562, 0.437793], Float32[-0.140227, -0.139971, -0.138966, -0.133971, -0.110061, -0.015614, -0.00221562], 0)
Stacktrace:
 [1] error(::String, ::Float64, ::Vararg{Any,N} where N) at .\error.jl:30
 [2] _hagerzhang!(::Optim.ManifoldObjective{NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::LineSearches.LineSearchResults{Float32}, ::Float32, ::Bool, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Int64, ::Float64, ::Int64) at C:\Users\user\.julia\v0.6\LineSearches\src\hagerzhang.jl:185
 [3] perform_linesearch!(::Optim.GradientDescentState{Float32,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{Float32,1},Array{Float32,1}}}, ::Optim.ManifoldObjective{NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}}) at C:\Users\user\.julia\v0.6\Optim\src\utilities\perform_linesearch.jl:47
 [4] update_state!(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Optim.GradientDescentState{Float32,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{Float32,1},Array{Float32,1}}}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/first_order\gradient_descent.jl:74
 [5] optimize(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{Float32,1},Array{Float32,1}}}, ::Optim.Options{Float64,Void}, ::Optim.GradientDescentState{Float32,1}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/optimize\optimize.jl:54
 [6] optimize(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{Float32,1},Array{Float32,1}}}, ::Optim.Options{Float64,Void}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/optimize\optimize.jl:18
 [7] #optimize#97(::Float32, ::Float32, ::Float32, ::Bool, ::Int64, ::Bool, ::Bool, ::Bool, ::Void, ::Int64, ::Void, ::Void, ::Float32, ::Float32, ::Float32, ::Optim.##98#107, ::Optim.Options{Float64,Void}, ::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:258
 [8] optimize(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:145
```

In another instance with `BigFloat`, which is more embedded in a much bigger code for my work, so it was hard to separate, I was getting the following error which was the reason I started investigating this problem in the first place. But I still cannot reproduce the exact error with a MWE, so I will get back to it tomorrow.
```julia
UndefRefError: access to undefined reference

Stacktrace:
 [1] maxdiff(::Array{BigFloat,1}, ::Array{BigFloat,1}) at C:\Users\user\.julia\v0.6\Optim\src\utilities\maxdiff.jl:2
 [2] optimize(::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{BigFloat,1},Array{BigFloat,1}}}, ::Optim.Options{Float64,Void}, ::Optim.GradientDescentState{BigFloat,1}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/optimize\optimize.jl:85
 [3] optimize(::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{BigFloat,1},Array{BigFloat,1}}}, ::Optim.Options{Float64,Void}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/optimize\optimize.jl:18
 [4] #optimize#97(::BigFloat, ::BigFloat, ::BigFloat, ::Bool, ::Int64, ::Bool, ::Bool, ::Bool, ::Void, ::Int64, ::Void, ::Void, ::BigFloat, ::BigFloat, ::BigFloat, ::Optim.##98#107, ::Optim.Options{Float64,Void}, ::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:258
 [5] optimize(::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:145
```

I haven't read Optim before so I am not confident enough playing around with the source code but I will try to solve the error tomorrow if I can and make a PR if I do. I really hope you beat me to it though :)

**Comment by pkofod** [comment] 2018-02-03 18:51
I will have a look, it seems straight forward for big float, but the float32 might be a precision thing

**Comment by pkofod** [comment] 2018-02-03 18:51
Try a different line search for the latter case

**Comment by mohamed82008** [comment] 2018-02-04 01:33
Running:
```julia
results = optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}(), linesearch=LineSearches.BackTracking())
```
with Float32 I got:
```julia
ERROR: MethodError: no method matching Optim.MultivariateOptimizationResults(::Optim.Fminbox{Optim.GradientDescent}, ::Bool, ::Array{Float32,1}, ::Array{Float32,1}, ::Float32, ::Int64, ::Bool, ::Bool, ::Float64, ::Float32, ::Bool, ::Float64, ::Float32, ::Bool, ::Float64, ::Float32, ::Bool, ::Array{Optim.OptimizationState{Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.BackTracking{Float64,Int64},Optim.InverseDiagonal,Optim.##104#113{Optim.##106#115,Array{Float32,1},Array{Float32,1}}}},1}, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  Optim.MultivariateOptimizationResults(::O<:Optim.AbstractOptimizer, ::Bool, ::Array{Tx,N}, ::Array{Tx,N}, ::Tf, ::Int64, ::Bool, ::Bool, ::T, ::T, ::Bool, ::T, ::T, ::Bool, ::T, ::T, ::Bool, ::M, ::Int64, ::Int64, ::Int64) where {O<:Optim.AbstractOptimizer, T, Tx, Tf, N, M} at C:\Users\user\.julia\v0.6\Optim\src\types.jl:73
Stacktrace:
 [1] #optimize#97(::Float32, ::Float32, ::Float32, ::Bool, ::Int64, ::Bool, ::Bool, ::Bool, ::Void, ::Int64, ::Void, ::LineSearches.BackTracking{Float64,Int64}, ::Float32, ::Float32, ::Float32, ::Optim.##106#115, ::Optim.Options{Float64,Void}, ::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:279
 [2] (::Optim.#kw##optimize)(::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::Optim.Fminbox{Optim.GradientDescent}) at .\<missing>:0
 [3] eval(::Module, ::Any) at .\boot.jl:235
```
Also using the default HagerZhang linesearch and one variable only, I am getting that same last error. So the weird Float32 error seems to be caused only when there are 2 or more variables and using HagetZhang.

**Comment by mohamed82008** [comment] 2018-02-04 07:25
I think I figured out the other error I was getting. Turns out if I start very close to the optimal solution and using BigFloat, `state.x_previous` will be `BigFloat[#undef, #undef]` because it was not initialized properly. So calling `maxdiff` gives `access to undefined reference`, something like this:
```julia
julia> a = Array{BigFloat}(2)
2-element Array{BigFloat,1}:
 #undef
 #undef

julia> a[1]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex(::Array{BigFloat,1}, ::Int64) at .\array.jl:554
```
Will try to make a fix.

**Comment by mohamed82008** [comment] 2018-02-04 07:40
The fix is simple, just changing `similar(initial_x)` to `copy(initial_x)` in the `initial_state` functions of all solver files. Now I am getting the same error in the MWE above!

**Comment by pkofod** [comment] 2018-02-04 08:19
Alright. All the errors that says something with multivariateoptimizationresults are already fixed on Master or in my latest pr. The slope issue only happens on float32 right ?

**Comment by pkofod** [comment] 2018-02-04 08:42
But yes, similar is dangerous if you don't guarantee that the variables are updated before they're used in any way. Copy may not result in errrors but we still need to be sure that it's not a bug somewhere else that the var is not updated

**Comment by mohamed82008** [comment] 2018-02-04 09:32
The slope error is with BigFloat.

**Comment by pkofod** [comment] 2018-02-04 10:14
When you say you use Optim 0.12.0+ is that then master, or is it because you've changed something in Optim yourself?

For what it's worth, here's what I get
```julia
julia> using Optim

julia> f(x::AbstractVector{T}) where {T} = (T(1.0) - x[1])^2 + T(100.0) * (x[2] - x[1]^2)^2
f (generic function with 1 method)

julia> function g!(storage::AbstractVector{T}, x::AbstractVector{T}) where {T}
          storage[1] = T(-2.0) * (T(1.0) - x[1]) - T(400.0) * (x[2] - x[1]^2) * x[1]
          storage[2] = T(200.0) * (x[2] - x[1]^2)
       end
g! (generic function with 1 method)

julia> T = BigFloat
BigFloat

julia> lower = T[1.25, -2.1]
2-element Array{BigFloat,1}:
  1.250000000000000000000000000000000000000000000000000000000000000000000000000000
 -2.100000000000000088817841970012523233890533447265625000000000000000000000000000

julia> upper = T[Inf, Inf]
2-element Array{BigFloat,1}:
 BigFloat(Inf, 256)
 BigFloat(Inf, 256)

julia> initial_x = T[2.0, 2.0]
2-element Array{BigFloat,1}:
 2.000000000000000000000000000000000000000000000000000000000000000000000000000000
 2.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> od = OnceDifferentiable(f, g!, initial_x)
NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}(f, g!, NLSolversBase.fg!, 0.000000000000000000000000000000000000000000000000000000000000000000000000000000, BigFloat[#undef, #undef], BigFloat[BigFloat(NaN, 256), BigFloat(NaN, 256)], BigFloat[BigFloat(NaN, 256), BigFloat(NaN, 256)], [0], [0])

julia> results = optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}())
Results of Optimization Algorithm
 * Algorithm: Fminbox with Gradient Descent
 * Starting Point: [2.000000000000000000000000000000000000000000000000000000000000000000000000000000,2.000000000000000000000000000000000000000000000000000000000000000000000000000000, ...]
 * Minimizer: [1.250000000000000000000000000000000000000000000000003001010417050381222892731148,1.562500000000000000000000000000004947915937216645000126402871101738638480233493, ...]
 * Minimum: 6.250000e-02
 * Iterations: 18
 * Convergence: true
   * |x - x'| ≤ 1.0e-32: false 
     |x - x'| = 5.92e-34 
   * |f(x) - f(x')| ≤ 1.0e-32 |f(x)|: true
     |f(x) - f(x')| = 3.78e-47 |f(x)|
   * |g(x)| ≤ 1.0e-08: false 
     |g(x)| = 5.00e-01 
   * Stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 19676
 * Gradient Calls: 19676

julia> T=Float32
Float32

julia> lower = T[1.25, -2.1]
2-element Array{Float32,1}:
  1.25
 -2.1 

julia> upper = T[Inf, Inf]
2-element Array{Float32,1}:
 Inf32
 Inf32

julia> initial_x = T[2.0, 2.0]
2-element Array{Float32,1}:
 2.0
 2.0

julia> od = OnceDifferentiable(f, g!, initial_x)
NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}(f, g!, NLSolversBase.fg!, 0.0f0, Float32[4.44352f-42, 0.0], Float32[NaN32, NaN32], Float32[NaN32, NaN32], [0], [0])

julia> results = optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}())
ERROR: c = 1.3308273992151953, lsr = LineSearches.LineSearchResults{Float32}(Float32[0.0, 0.000425865, 0.00212932, 0.0106466, 0.0532331, 0.266165, 1.33083], Float32[0.412871, 0.412811, 0.412573, 0.411411, 0.406221, 0.393562, 0.437793], Float32[-0.140227, -0.139971, -0.138966, -0.133971, -0.110061, -0.015614, -0.00221562], 0)
Stacktrace:
 [1] error(::String, ::Float64, ::Vararg{Any,N} where N) at ./error.jl:30
 [2] _hagerzhang!(::Optim.ManifoldObjective{NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::LineSearches.LineSearchResults{Float32}, ::Float32, ::Bool, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Int64, ::Float64, ::Int64) at /home/pkm/.julia/v0.6/LineSearches/src/hagerzhang.jl:185
 [3] perform_linesearch!(::Optim.GradientDescentState{Array{Float32,1},Float32}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##125#134{Optim.##119#128,Array{Float32,1},Array{Float32,1}}}, ::Optim.ManifoldObjective{NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}}) at /home/pkm/.julia/v0.6/Optim/src/utilities/perform_linesearch.jl:47
 [4] update_state!(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Optim.GradientDescentState{Array{Float32,1},Float32}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##125#134{Optim.##119#128,Array{Float32,1},Array{Float32,1}}}) at /home/pkm/.julia/v0.6/Optim/src/multivariate/solvers/first_order/gradient_descent.jl:74
 [5] optimize(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##125#134{Optim.##119#128,Array{Float32,1},Array{Float32,1}}}, ::Optim.Options{Float64,Void}, ::Optim.GradientDescentState{Array{Float32,1},Float32}) at /home/pkm/.julia/v0.6/Optim/src/multivariate/optimize/optimize.jl:55
 [6] optimize(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##125#134{Optim.##119#128,Array{Float32,1},Array{Float32,1}}}, ::Optim.Options{Float64,Void}) at /home/pkm/.julia/v0.6/Optim/src/multivariate/optimize/optimize.jl:19
 [7] #optimize#118(::Float32, ::Float32, ::Float32, ::Bool, ::Int64, ::Bool, ::Bool, ::Bool, ::Void, ::Int64, ::Void, ::Void, ::Float32, ::Float32, ::Float32, ::Optim.##119#128, ::Optim.Options{Float64,Void}, ::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::Optim.Fminbox{Optim.GradientDescent}) at /home/pkm/.julia/v0.6/Optim/src/multivariate/solvers/constrained/fminbox.jl:258
 [8] optimize(::NLSolversBase.OnceDifferentiable{Float32,Array{Float32,1},Array{Float32,1},Val{false}}, ::Array{Float32,1}, ::Array{Float32,1}, ::Array{Float32,1}, ::Optim.Fminbox{Optim.GradientDescent}) at /home/pkm/.julia/v0.6/Optim/src/multivariate/solvers/constrained/fminbox.jl:145
```
on https://github.com/JuliaNLSolvers/Optim.jl/pull/520

**Comment by mohamed82008** [comment] 2018-02-04 10:48
I am using commit 7b4f8cb and only changed the second line of maxdiff.jl to 
`res = zero(promote_type(eltype(x), eltype(y)))`. Could you try taking the solution and using it as the initial solution for another run using BigFloat to reproduce the function value/slope error?

**Comment by pkofod** [comment] 2018-02-04 10:48
Also, as I mentioned, you should try changing the line search. For example `Static` (fixed step size) goes through:

```julia
julia> results = optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}(); linesearch=LineSearches.Static(alpha=0.0001))
Results of Optimization Algorithm
 * Algorithm: Fminbox with Gradient Descent
 * Starting Point: [2.0,2.0]
 * Minimizer: [-5.3103404,-14.906098]
 * Minimum: 1.858509e+05
 * Iterations: 1000
 * Convergence: false
   * |x - x'| ≤ 1.0e-32: false 
     |x - x'| = 1.84e-02 
   * |f(x) - f(x')| ≤ 1.0e-32 |f(x)|: false
     |f(x) - f(x')| = NaN |f(x)|
   * |g(x)| ≤ 1.0e-08: false 
     |g(x)| = 1.73e-01 
   * Stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: true
 * Objective Calls: 1001005
 * Gradient Calls: 1001000
```

and backtracking  find something close to the minimizer, although the gradient isn't below 1e-8 (maximum number of iterations was reached)

**Comment by pkofod** [comment] 2018-02-04 10:51
Can you try to check out master and see if you can reproduce?

**Comment by mohamed82008** [comment] 2018-02-04 10:54
Awesome, seems fixed!

**Comment by mohamed82008** [comment] 2018-02-04 10:55
What do you think resolved the error?

**Comment by pkofod** [comment] 2018-02-04 12:51
Well, I'm only sure why the MulitvariateOptimizationResults error stopped happening, I don't know about the other one. Are you sure the other errors don't still happen at random?

**Comment by mohamed82008** [comment] 2018-02-04 13:11
They still happen in my topology optimization code but not in the example above.

**Comment by pkofod** [comment] 2018-02-04 13:28
Sorry for being dense, but can you post below this post the errors that you're getting now? Just so we don't talk about two different things.

**Comment by mohamed82008** [comment] 2018-02-04 13:38
Sorry I wasn't clear. It's this error, which disappears when I replace `similar` with `copy`.
```julia
UndefRefError: access to undefined reference

Stacktrace:
 [1] maxdiff(::Array{BigFloat,1}, ::Array{BigFloat,1}) at C:\Users\user\.julia\v0.6\Optim\src\utilities\maxdiff.jl:2
 [2] optimize(::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{BigFloat,1},Array{BigFloat,1}}}, ::Optim.Options{Float64,Void}, ::Optim.GradientDescentState{BigFloat,1}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/optimize\optimize.jl:85
 [3] optimize(::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Optim.GradientDescent{LineSearches.InitialPrevious{Float64},LineSearches.HagerZhang{Float64},Optim.InverseDiagonal,Optim.##104#113{Optim.##98#107,Array{BigFloat,1},Array{BigFloat,1}}}, ::Optim.Options{Float64,Void}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/optimize\optimize.jl:18
 [4] #optimize#97(::BigFloat, ::BigFloat, ::BigFloat, ::Bool, ::Int64, ::Bool, ::Bool, ::Bool, ::Void, ::Int64, ::Void, ::Void, ::BigFloat, ::BigFloat, ::BigFloat, ::Optim.##98#107, ::Optim.Options{Float64,Void}, ::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:258
 [5] optimize(::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Optim.Fminbox{Optim.GradientDescent}) at C:\Users\user\.julia\v0.6\Optim\src\multivariate/solvers/constrained\fminbox.jl:145
```

**Comment by pkofod** [comment] 2018-02-04 13:41
What about the Float32 error with the linesearch?

**Comment by mohamed82008** [comment] 2018-02-04 13:50
But not with other line search techniques like BackTracking and Static, these work fine.

**Comment by pkofod** [comment] 2018-02-04 14:01
Alright, so two different errors. Good, we're getting somewhere :) The first error can be tackled easily, but the other one is a bit tricky. I've suspected for some time that there is something weird going on with HagerZhang, and I will have to figure that out. Could you try MoreThuente() ? That should be pretty good, but might not fail here.

**Comment by mohamed82008** [comment] 2018-02-04 14:12
Yup MoreThuente works fine. I am not really concerned with the line search technique for now, I just want to get correct high and arbitrary precision.

**Comment by pkofod** [comment] 2018-02-04 15:12
Alright, so the problem is that you essentially start at the solution right? Then the loop is completely bypassed, and `abs_change(state)` will try to take a difference between `initial_x` and an uninitialized `x`. The only reason why we didn't catch this earlier (because we have discussed and implemented convergence checks before we start the loop) is because `Array{Float64, N}()` will produce actual Float64's in there, so we can compute maxdiff, but BigFloat's are `#undef`'s as you pointed out. Good to catch this bug! I'll fix it.

**Comment by mohamed82008** [comment] 2018-02-04 15:24
I am not 100% sure this is the (only) problem anymore, because when I do the same in the above example, i.e. starting at the optimal solution, it does not give the error, so something is fishy. But I think this is the problem in my code as it goes away when replacing `similar` with `copy` and yes I do start very close to the optimal solution sometimes. I don't have time to dig deeper why the error isn't happening in the above example, but maybe when I read Optim, I will figure it out one day! Thanks for your efforts btw, really appreciate it :)

**Comment by mohamed82008** [comment] 2018-02-05 12:45
Btw, replacing `!=` with `\napprox` in line 184 of LineSearches/src/hagerzhang.jl solves the Float32 precision problem.

**Comment by pkofod** [comment] 2018-02-05 12:49
> Btw, replacing != with \napprox in line 184 of LineSearches/src/hagerzhang.jl solves the Float32 precision problem.

cc @anriseth 

Okay! We'll look into it. The thing with stuff like HagerZhang and MoreThuente is, that they're quite carefully written for double precision ieee 754 floats, so we're actually breaching the contract with their software in the sense that their give no guarantees for say single precision or extended precision inputs.

**Comment by mohamed82008** [comment] 2018-02-05 12:51
Alternatively, this also works `T(c) != lsr.alpha[ib]`.

**Comment by pkofod** [comment] 2018-02-05 13:09
> Alternatively, this also works, T(c) != lsr.alpha[ib], which has the advantage of not changing the behavior of the Float64 case if that behavior is best left untouched for the reason you mentioned.

Yeah, I'm not saying what you're suggesting is wrong, I'm just saying I havn't had time to think about it yet :) Appreciate your input, though! Good BigFloat support is high on my priority list

**Comment by mohamed82008** [comment] 2018-02-05 13:10
Awesome, looking forward to the outcome!

**Comment by mohamed82008** [comment] 2018-02-06 05:37
#510

**Comment by pkofod** [comment] 2019-05-25 21:14
Better late than never? :)

**Closed** 2019-05-25 21:14 UTC

**Comment by mohamed82008** [comment] 2019-05-28 00:54
Definitely!
