### ISSUE TITLE
Type instability in `result` object

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/Optim.jl#510] opened 2018-01-18 09:09 UTC
This is currently the only source of type instability in my code:
```julia
using Optim
function f()
   rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
   result = optimize(rosenbrock, zeros(2), BFGS())
   return result
end
@code_warntype f()
#=
Variables:
  #self# <optimized out>
  rosenbrock <optimized out>
  result::Optim.MultivariateOptimizationResults{Optim.BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64},Optim.##64#66},Float64,1,_} where _
  #64 <optimized out>
  d::NLSolversBase.OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1},Val{false}}
=#
```
I would appreciate your help eliminating it. Thank you.

**Comment by pkofod** [comment] 2018-01-18 09:22
Are you on master Julia and Master Optim, or? I'd love to know your Julia versioninfo and `Pkg.status()`

**Comment by pkofod** [comment] 2018-01-18 09:25
I think this is the problem https://github.com/JuliaNLSolvers/Optim.jl/compare/master...pkofod-patch-5?quick_pull=1

**Comment by mohamed82008** [comment] 2018-01-18 09:38
Great responsiveness! I am on Julia v0.6.2 with Optim v0.11.0. My Pkg.status() is enormous but here is the version info.
```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by mohamed82008** [comment] 2018-01-18 10:14
FWIW, I had a similar problem when trying to resolve a type instability in MMA.jl which defines its own `Optim.MultivariateOptimizationResults` version with another subtype of `Optim.Optimizer`. Julia wouldn't just infer that last parameter no matter what. Even with assertion, it would first making a type unstable temporary then a type stable one. The only way I could resolve this is by explicitly adding the parameters in the constructor of the `Optim.MultivariateOptimizationResults`. Not sure if this is a Julia bug or if I am missing on something but you might want to try that solution.

**Comment by pkofod** [comment] 2018-01-18 12:15
Thanks, I could do that. I'll report back later :)

**Comment by pkofod** [comment] 2018-01-19 10:48
Could you try to check out master? It seems to be fixed here now that #511 is merged, but just to make sure that we can close this  issue.

**Comment by mohamed82008** [comment] 2018-01-19 11:12
Yes it is, I still didn't commit some changes though. I will make a PR when I am happy with the performance ;) Is the fix on Optim master?

**Comment by mohamed82008** [comment] 2018-01-19 11:15
Hmm, I am getting this when I try to checkout master:
```julia
julia> Pkg.checkout("Optim")
INFO: Checking out Optim master...
INFO: Pulling Optim latest master...
WARNING: julia is fixed at 0.6.2 conflicting with requirement for ResumableFunctions: [0.7.0,∞)
ERROR: Unsatisfiable requirements detected for package NLSolversBase:
├─version range [4.0.0,∞) required by package Optim, whose only allowed version is 0.12.0+:
│ └─version 0.12.0+ set by fixed requirement (package is checked out, dirty or pinned)
├─version range [3.0.0,∞) required by package LineSearches, whose allowed version range is [3.2.0,∞):
│ ├─version range [3.2.0,∞) required by package Optim, whose only allowed version is 0.12.0+:
│ │ └─[see above for Optim backtrace]
│ └─version range [0.0.0-,∞) required by package NLsolve, whose allowed version range is [0.7.3,∞):
  │ ├─version range [0.7.3,∞) required by package FiniteElementDiffEq, whose allowed version range is [0.0.0-,∞):
│   │ └─version range [0.0.0-,∞) set by an explicit requirement
  │ └─version range [0.7.3,∞) required by package OrdinaryDiffEq, whose allowed version range is [0.0.0,∞):
    │ └─version range [0.0.0,∞) required by package DifferentialEquations, whose allowed version range is [0.0.0-,∞):
      │ └─version range [0.0.0-,∞) set by an explicit requirement
└─version range [0.0.1,4.0.0) required by package NLsolve, whose allowed version range is [0.7.3,∞):
  └─[see above for NLsolve backtrace]
The intersection of the requirements is empty.
```

**Comment by pkofod** [comment] 2018-01-19 11:53
> s the fix on Optim master?

Yes

> Hmm, I am getting this when I try to checkout master:

Okay, then don't bother. I'll just assume that it's fixed which is probably a good a assumption since it's fixed here. Please reopen if the problem is still there when we get to the new version.

**Comment by mohamed82008** [comment] 2018-01-19 12:00
Cool, I will post a discourse question on the above requirements conflict. Thanks a lot!

**Comment by mohamed82008** [comment] 2018-02-06 04:02
Problem is back!

**Comment by pkofod** [comment] 2018-02-06 09:46
With the original code stump?

**Comment by mohamed82008** [comment] 2018-02-06 17:39
Seems to be a perk of the keyword arguments of the Options argument and constructor. The following infers just fine:
```julia
function f()
    rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
    method = BFGS()
    x_tol = 1e-32
    f_tol = 1e-32
    g_tol = 1e-8
    f_calls_limit = 0
    g_calls_limit = 0
    h_calls_limit = 0
    allow_f_increases = false
    iterations = 1_000
    store_trace = false
    show_trace = false
    extended_trace = false
    show_every = 1
    callback = nothing
    time_limit = NaN
    options = Optim.Options{Float64,Void}(x_tol, f_tol, g_tol, f_calls_limit, g_calls_limit, h_calls_limit, allow_f_increases, iterations, store_trace, show_trace, extended_trace, show_every, callback, time_limit)
    result = optimize(rosenbrock, zeros(2), BFGS(), options)
    return result
end
@code_warntype f()
```

**Comment by mohamed82008** [comment] 2018-02-06 17:40
Perhaps switch to positional arguments?

**Comment by mohamed82008** [comment] 2018-02-06 17:41
Doesn't seem to be exported anyways, and can still keep keyword argument version for API if you want to export it.

**Comment by mohamed82008** [comment] 2018-02-06 17:53
Yes the original code.

**Comment by mohamed82008** [comment] 2018-02-06 17:56
This on the other hand doesn't infer.
```julia
function f()
	rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
	method = BFGS()
	options = Optim.Options(;Optim.default_options(method)...)
	result = optimize(rosenbrock, zeros(2), BFGS(), options)
	return result
end
f()
@code_warntype f()
```

**Comment by mohamed82008** [comment] 2018-02-06 17:58
If `default_options` returns an Options object directly (as it has all the information needed for that already), I think the problem will be sorted out. The Options keyword outer constructor could be left for an API.

**Comment by mohamed82008** [comment] 2018-02-06 18:01
Or perhaps I just use the workaround in my work and you can wait for v0.7 😄

**Comment by mohamed82008** [comment] 2018-02-06 18:22
The above workaround infers only when I change optimize to:
```julia
function optimize(d::D, initial_x::Tx, method::M,
                  options::Options{T, TCallback} = Options(;default_options(method)...),
                  state = initial_state(method, options, d, complex_to_real(d, initial_x))) where {D<:AbstractObjective, M<:AbstractOptimizer, Tx<:AbstractArray, T, TCallback}
    .
    .
    .

    after_while!(d, state, method, options)

    # we can just check minimum, as we've earlier enforced same types/eltypes
    # in variables besides the option settings
    Tf = typeof(value(d))
    f_incr_pick = f_increased && !options.allow_f_increases

    return MultivariateOptimizationResults{typeof(method),T,Tx,typeof(x_abschange(state)),Tf,typeof(tr)}(method,
                NLSolversBase.iscomplex(d),
                real_to_complex(d, initial_x),
                real_to_complex(d, pick_best_x(f_incr_pick, state)),
                pick_best_f(f_incr_pick, state, d),
                iteration,
                iteration == options.iterations,
                x_converged,
                T(options.x_tol),
                x_abschange(state),
                f_converged,
                T(options.f_tol),
                f_abschange(d, state),
                g_converged,
                T(options.g_tol),
                g_residual(d),
                f_increased,
                tr,
                f_calls(d),
                g_calls(d),
                h_calls(d))
end
```

**Comment by pkofod** [comment] 2018-02-06 19:54
Alright, I'll see what I can do. I know it's annoying, but I actually don't think it'll matter for performance that much. But I'll fix it. I promise :)

**Comment by mohamed82008** [comment] 2018-02-06 20:15
Thanks! I have been trying to fix an even nastier type instability in Fminbox for a while now, and I feel like I got to a dead end in terms of useful info that `@code_warntype` is giving me. The following code is what I am trying to make type stable:
```julia
using Optim
f(x::AbstractVector{T}) where {T} = (T(1.0) - x[1])^2 + T(100.0) * (x[2] - x[1]^2)^2
function g!(storage::AbstractVector{T}, x::AbstractVector{T}) where {T}
      storage[1] = T(-2.0) * (T(1.0) - x[1]) - T(400.0) * (x[2] - x[1]^2) * x[1]
      storage[2] = T(200.0) * (x[2] - x[1]^2)
end
T = BigFloat
lower = T[1.25, -2.1]
upper = T[Inf, Inf]
initial_x = T[2.0, 2.0]
od = OnceDifferentiable(f, g!, initial_x)
results = optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}())
@code_warntype optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}())
```

Here is the output of `@code_warntype`:
```julia
julia> @code_warntype optimize(od, initial_x, lower, upper, Fminbox{GradientDescent}())
Variables:
  #self#::Optim.#optimize
  df::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}
  initial_x::Array{BigFloat,1}
  l::Array{BigFloat,1}
  u::Array{BigFloat,1}
  #temp#::Optim.Fminbox{Optim.GradientDescent}
  x_tol::BigFloat
  f_tol::BigFloat
  g_tol::BigFloat
  allow_f_increases::Bool
  iterations <optimized out>
  store_trace::Bool
  show_trace::Bool
  extended_trace::Bool
  callback::Void
  show_every <optimized out>
  alphaguess::Void
  linesearch::Void
  eta <optimized out>
  mu0 <optimized out>
  mufactor <optimized out>
  precondprep <optimized out>
  optimizer_o::Optim.Options{BigFloat,Void}
  #119::Optim.##119#128
  z@_25::BigFloat
  z@_26::BigFloat
  z@_27::BigFloat

Body:
  begin
      x_tol::BigFloat = $(Expr(:invoke, MethodInstance for eps(::Type{BigFloat}), :(Optim.eps), :($(Expr(:static_parameter, 1)))))
      f_tol::BigFloat = $(Expr(:invoke, MethodInstance for sqrt(::BigFloat), :(Optim.sqrt), :($(Expr(:invoke, MethodInstance for eps(::Type{BigFloat}), :(Optim.eps), :($(Expr(:static_parameter, 1))))))))
      g_tol::BigFloat = $(Expr(:invoke, MethodInstance for sqrt(::BigFloat), :(Optim.sqrt), :($(Expr(:invoke, MethodInstance for eps(::Type{BigFloat}), :(Optim.eps), :($(Expr(:static_parameter, 1))))))))
      allow_f_increases::Bool = true
      store_trace::Bool = false
      show_trace::Bool = false
      extended_trace::Bool = false
      callback::Void = Optim.nothing
      alphaguess::Void = Optim.nothing
      linesearch::Void = Optim.nothing
      $(Expr(:inbounds, false))
      # meta: location mpfr.jl convert 98
      z@_25::BigFloat = $(Expr(:invoke, MethodInstance for BigFloat(), :(Base.MPFR.BigFloat))) # line 99:
      SSAValue(2) = (Core.getfield)(Base.MPFR.ROUNDING_MODE, :x)::Int32
      $(Expr(:foreigncall, ("mpfr_set_d", :libmpfr), Int32, svec(Ptr{BigFloat}, Float64, Int32), :(&z@_25), :(z@_25), 0.4, 0, SSAValue(2), 0))
      # meta: pop location
      $(Expr(:inbounds, :pop))
      $(Expr(:inbounds, false))
      # meta: location mpfr.jl convert 98
      z@_26::BigFloat = $(Expr(:invoke, MethodInstance for BigFloat(), :(Base.MPFR.BigFloat))) # line 99:
      SSAValue(5) = (Core.getfield)(Base.MPFR.ROUNDING_MODE, :x)::Int32
      $(Expr(:foreigncall, ("mpfr_set_d", :libmpfr), Int32, svec(Ptr{BigFloat}, Float64, Int32), :(&z@_26), :(z@_26), :(Optim.NaN), 0, SSAValue(5), 0))
      # meta: pop location
      $(Expr(:inbounds, :pop))
      $(Expr(:inbounds, false))
      # meta: location mpfr.jl convert 98
      z@_27::BigFloat = $(Expr(:invoke, MethodInstance for BigFloat(), :(Base.MPFR.BigFloat))) # line 99:
      SSAValue(8) = (Core.getfield)(Base.MPFR.ROUNDING_MODE, :x)::Int32
      $(Expr(:foreigncall, ("mpfr_set_d", :libmpfr), Int32, svec(Ptr{BigFloat}, Float64, Int32), :(&z@_27), :(z@_27), 0.001, 0, SSAValue(8), 0))
      # meta: pop location
      $(Expr(:inbounds, :pop))
      #119::Optim.##119#128 = $(Expr(:new, :(Optim.##119#128)))
      optimizer_o::Optim.Options{BigFloat,Void} = $(Expr(:new, Optim.Options{BigFloat,Void}, :(x_tol), :(f_tol), :(g_tol), 0, 0, 0, :(allow_f_increases), 1000, :(store_trace), :(show_trace), :(extended_trace), 1, :($(QuoteNode(nothing))), :(Optim.NaN)))
      return $(Expr(:invoke, MethodInstance for #optimize#118(::BigFloat, ::BigFloat, ::BigFloat, ::Bool, ::Int64, ::Bool, ::Bool, ::Bool, ::Void, ::Int64, ::Void, ::Void, ::BigFloat, ::BigFloat, ::BigFloat, ::Optim.##119#128, ::Optim.Options{BigFloat,Void}, ::Array{Any,1}, ::Optim.#optimize, ::NLSolversBase.OnceDifferentiable{BigFloat,Array{BigFloat,1},Array{BigFloat,1},Val{false}}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Array{BigFloat,1}, ::Optim.Fminbox{Optim.GradientDescent}), :(Optim.#optimize#118), :(x_tol), :(f_tol), :(g_tol), :(allow_f_increases), 1000, :(store_trace), :(show_trace), :(extended_trace), :(callback), 1, :(alphaguess), :(linesearch), :(z@_25), :(z@_26), :(z@_27), :(#119), :(optimizer_o), :($(Expr(:foreigncall, :(:jl_alloc_array_1d), Array{Any,1}, svec(Any, Int64), Array{Any,1}, 0, 0, 0))), :(#self#), :(df), :(initial_x), :(l), :(u), :(#temp#)))
  end::Optim.MultivariateOptimizationResults{_,_,_,_,_,_} where _ where _ where _ where _ where _ where _
```
given that I am using a fully parametric constructor and a type assertion!!!! I think I will just let it be for now. If you cannot figure it out, maybe I can ask for help on Discourse.

**Comment by pkofod** [comment] 2018-02-06 21:46
I think we need to take a good hard look at MultivariateOptimizationResults :)

**Comment by mohamed82008** [comment] 2018-02-06 22:52
Actually what's interesting is that it is not showing any of the variables used in the function. I will look further into it some time later.

**Comment by mohamed82008** [comment] 2018-02-06 23:41
Could the function be too big!? Perhaps if I decrease its size, everything might magically work out 😄. I might actually try that later.

**Comment by pkofod** [comment] 2018-02-07 06:43
Oh, in the code stump you have shown most recently, what you're seeing is the step where Julia looks at the keyword argument, and then passes them on to a method of said function with only positional arguments. This is called a function barrier, and makes sure that the actual call to `optimize` is efficient. Though I cannot say much more about this until I get to sit down and have a look one of these days.

**Comment by mohamed82008** [comment] 2018-02-07 06:53
If you are talking about the Fminbox code above, this is after I changed the keyword arguments to positional.

**Comment by mohamed82008** [comment] 2018-02-07 06:54
But maybe you are right and I did something wrong, I will double check later.

**Closed** 2020-02-13 23:35 UTC
